baseURL = "https://aan-news.proffer.dev"
languageCode = "en-us"
title = "AAN World News"
theme = "aan-world-news"
paginate = 8
paginatePath = "posts"

[params]
  description = "AAN is a privately-owned, independent news broadcaster that provides global coverage of worldwide events and conflicts."
  subTitle = "Our World, Your News"
  logo = "/images/aan-world-news-logo.png"

[taxonomies]
  profile = "profiles"
  tag = "tags"
  category = "categories"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "world"
    name = "World"
    url = "/world/"
    weight = 2

  [[menu.main]]
    identifier = "travel"
    name = "Travel"
    url = "/travel/"
    weight = 3

  [[menu.tags]]
    identifier = "europe"
    name = "europe"
    url = "/tags/europe/"
    weight = 1
  
  [[menu.tags]]
    identifier = "oceania"
    Name = "oceania"
    url = "/tags/oceania/"
    weight = 2