# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Aan World News"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Fictional Arma 3 / AAN World News theme."
homepage = "http://example.com/"
tags = ["arma", "news", "articles"]
features = ["profiles"]
min_version = "0.41"

[author]
  name = "Jacob Proffer"
  homepage = "https://proffer.dev"
